### ISSUE TITLE
Chat Commands Not Saving

### ISSUE THREAD

**Issue by TornadoXAlpha** [MrNobody98/morecommands#10] opened 2017-11-02 00:25 UTC
This Mod Is Just Great But The ChatChannels Is kind a corrupted it's didn't save any thing at all but

When i reload My Map And Try To Join the channel i created says you already in when i leave says the channel dose not exist
-----
Ahh..! Almost Forget The Chat Style Are The Same Didn't Save Any Thing I am Using MC1.12 Mod v6

whin i go to search on the web site you made i saw it's supposed to create a file chatChannels.json put i didn't found it so i created it and put the examples you add and edited it and still not working

Help me Please Fast As You Can Because This Mod Are Awesome

**Comment by MrNobody98** [comment] 2017-11-03 09:25
The information you provide (or the lack of those) don't tell me anything at all to fix your issue, heck I can't even tell exactly what your issue is. Please give me precise information like:

- What commands did you type in the chat
- What are the contents of the chatChannels.json file
- The Log File

Otherwise I can't do anything because I can't reproduce your bug.

(You should read the following, this describes what's important for a good bug report froma developer's point of view: http://www.chiark.greenend.org.uk/~sgtatham/bugs.html)

**Comment by TornadoXAlpha** [comment] 2017-11-03 21:14
My issue Is Very Simple {Nothing saving}
And I'AM in singleplayer

1. What commands did you type in the chat?

- Ok I Saw the chatchannels Tutorial and i'am used all chat channels commands..!

2. What are the contents of the chatChannels.json file?

- this file is on you'r web site || And i didn't Found it
Here--> http://morecommands.bplaced.net/content/usage/chatchannels.php
In-->4.Storage of Chat Channels: | Located in config/morecommands

3. The Log File
[latest.log](https://github.com/MrNobody98/morecommands/files/1442493/latest.log)

I Hope You Understand me and Sorry for misunderstanding..! {At last my issue is nothing saving}

**Comment by MrNobody98** [comment] 2017-11-06 20:13
Sorry for the late response, I was really busy the last days so I had almost no time to do anything related to MoreCommands. However I figured out that there was indeed a little bug which caused the chat channels not being saved (I didn't see this because it affects only the newer versions). Also there was a really small syntax error in the example on the website. Both problems are fixed now, just redownload the mod and everythin should work fine

**Closed by MrNobody98** 2017-11-06 20:13 UTC
