### ISSUE TITLE
[BUG] conflict between MoreCommands-1.11.2-5.0 and BetterFoliage-MC1.11.2-2.1.3

### ISSUE THREAD

**Issue by Tsoccerguy3** [MrNobody98/morecommands#5] opened 2017-03-16 05:58 UTC
On login to a Multiplayer server the world is invisible . 
[BUG] conflict between MoreCommands-1.11.2-5.0 and BetterFoliage-MC1.11.2-2.1.3

**Comment by MrNobody98** [comment] 2017-03-16 16:55
I downloaded the BetterFoliage mod and tried this out for myself. Everything's fine for me. I know that sometimes it can happen that the world is invisible (this happens to me sometimes as well), even in singleplayer. However the source of this bug is vanilla code. I'm not entirely sure why and when this happens and whether it happens only in combination with MoreCommands and/or other mods or without any mods at all but usually this issue can easily be solved by leaving and rejoining the world.

If this bug keeps occurring consistently for you, I need some more information to reproduce this bug because if I'm not able to see this for myself, there's no way for me to tell what the source is and I can't fix it.

**Comment by Tsoccerguy3** [comment] 2017-03-17 02:49
usining forge-1.11.2-13.20.0.2259 and just the 2 plugins to test , only happens logging into spigot . But your right about having to re-login 2 or 3 times before I begin to see the world rendering . The world is always there but can't see it . Have a AMD R9 280x Graphics Card . No crashes involved . I'll send you a Priv Msg with a link to the logs . I Think its a conflict in Net Handler bno.class

**Comment by MrNobody98** [comment] 2017-03-17 12:58
Ok, so this issue appears consistently only on spigot servers and for other servers it doesn't (except for the 2-3 relogins), right? Does it occur only when both, BetterFoliage and MoreCommands are installed or even if only MoreCommands is installed? Because the log file doesn't show anything useful and if it is a conflict which only appears for this specific combination (Spigot, BetterFoliage and MoreCommands) it can be a bit tricky to find the source but I might have an idea where to look for the source of this issue.

**Comment by Tsoccerguy3** [comment] 2017-04-05 04:53
I compiled the mod with your latest commit , Yes it has the same side effect , with some other mods as well.
In single player on first login to a map it's invisible , I log out and back in it begins to render . In Multiplayer , I first login to a server and 1 chunk renders , I re - login 1 or 2 times to get the world to render. No errors , just invisible . I have about 20 mods normally mostly cosmetic and utility
`01/24/2017  10:10 AM            88,439 BetterSprinting  MC-1.11.2  v1.1.9.jar
03/10/2017  03:35 AM           139,749 bigtrees-1.11.2-0.3-1.jar
02/27/2017  03:17 AM           432,671 CoralReef-1.3_1.11.2.jar
04/01/2017  05:54 PM        11,573,112 DynamicSurroundings-1.11.2-3.3.3.1.jar
03/23/2017  12:04 AM         5,377,692 FastAsyncWorldEdit-forge111-17.03.22-661f02d-588-11.7.13.jar
01/11/2017  02:41 AM            19,302 GlobalGameRules-1.11-2.0.jar
04/04/2017  07:52 PM           502,551 jei_1.11.2-4.3.1.255.jar
02/23/2017  01:41 PM         1,561,228 liteloader-1.11.2-SNAPSHOT-release.jar
04/05/2017  12:29 AM           829,970 modid-1.0.jar
02/02/2017  06:55 PM             6,077 NetherPortalFix_1.11.2-4.3.0.jar
12/28/2016  11:07 PM            63,434 OfflineSkins-1.11.2-v1.jar
01/17/2017  06:40 PM           676,997 paintings-1.11-3.2.0.1.jar
04/01/2017  07:51 AM         2,045,453 preview_OptiFine_1.11.2_HD_U_B8_pre.jar
02/01/2017  03:20 PM           832,450 progenitor-0.0.4+1.11.2.jar
02/02/2017  09:33 PM            72,997 PSG Revamper-1.11.2-1.0.0.0.jar
02/14/2017  01:18 AM         1,357,449 RTG-1.11.2-5.1.0.0-alpha.1.jar
01/21/2017  08:52 AM            42,039 SoundFilters-0.9_for_1.11.2.jar
01/19/2017  02:49 PM            55,857 StepUp-4.0-mc1.11.jar
03/19/2017  03:51 PM            31,525 TTFR-1.11.2-1.7.3.jar
02/20/2017  01:25 PM           460,785 WorldEdit CUI Forge Edition 2-2.0.1-mf-1.11.2-13.20.0.2228.jar
03/29/2017  08:47 PM         1,466,109 worldedit-forge-mc1.11.2-6.1.7-SNAPSHOT-dist.jar
03/16/2017  03:56 PM           306,550 WorldHandler-1.11.2-4.6.jar
01/29/2017  02:19 PM         3,933,868 BetterFoliage-MC1.11.2-2.1.3.jar1
02/23/2017  10:33 AM           148,745 BetterFps-1.4.2_1.11.2.jar1
01/20/2017  11:17 AM            37,838 mod_chatBubbles-1.0.1_for_1.11.2.litemod
01/29/2017  10:21 PM           583,830 mod_voxelMap_1.6.21_for_1.11.2.litemod
01/01/2017  10:00 PM             8,060 mod-gammabright-3.7-mc1.11.2.litemod
04/01/2017  06:01 PM           302,620 mod-litemodwdl-4.0.0.4-SNAPSHOT-mc1.11.2.litemod
12/31/2016  03:12 AM           274,982 mod-litemodwdl1.11.2_gradle-1.11.2a-beta1-mc1.11.2_NoDRM.litemod1
09/16/2016  09:55 PM           375,492 CmdLstMoreCommands.pdf`

**Comment by MrNobody98** [comment] 2017-04-07 18:44
I'm such an idiot not to see why this happens. Since Minecraft 1.8 all networking stuff is done asynchronously (on a separate thread). Since I make all the changes for a new version in one version (namely 1.7.10) and only adapt the changes for the other versions I forgot to handle changes to game objects synchronously. This should be the cause of all your troubles and I have fixed it now. Download links are the same.

**Comment by Tsoccerguy3** [comment] 2017-04-08 04:15
Just tried the new version combined with plugins above , logged in to a spigot server
![2017-04-07_23 20 44](https://cloud.githubusercontent.com/assets/22108822/24825639/42cf970c-1bf0-11e7-9146-9f88f7a913f3.png)
![2017-04-07_23 21 38](https://cloud.githubusercontent.com/assets/22108822/24825642/46997fd8-1bf0-11e7-8a40-446f3636853b.png)

**Comment by MrNobody98** [comment] 2017-04-08 11:52
That's weird, it should really have fixed this. The problem with concurrency issues is that they appear only sometimes so it's hard to test whether everything's working properly. I'm running out of ideas where to look for the source of this bug because I tried it in singleplayer with BetterFoliage installed and everything works fine so it can't be a conflict with BetterFoliage alone. With so many mods installed it's hard to figure out which ones have a conflict. Your problem is also a little bit different from what I have seen so far since one chunk is rendering. The world rendering issues I observed were simply that the world was not rendering at all so it might have a different cause and the new version fixed the latter bug but not the one you observed. Anyway I'll have another look into it with exactly the same mods as you. Maybe I can figure out the source of this issue this way.

**Comment by Tsoccerguy3** [comment] 2017-04-10 16:43
I've had to pull the mod for now . Chunks not rendering sometimes , can not be corrected by re-logon . Happens in Single and Multiplayer , The sources are available for better foliage https://github.com/octarine-noise/BetterFoliage/tree/kotlin-1.9.4

it might also happen with some others

**Comment by Tsoccerguy3** [comment] 2017-04-15 13:03
Seems to work without problems on the server side using sponge forge 1.11.2. When I get some time I will check the mods 1 at a time to find what class is causing the client issue .

**Comment by MrNobody98** [comment] 2017-04-15 13:28
Good to know. Unfortunately I was too busy last week to further investigate this myself but hopefully I'll be able to fix this bug this week.

**Comment by MrNobody98** [comment] 2017-05-20 14:17
So... a month later and I have tried to reproduce this bug for myself to see what causes it but no matter what I did, everything worked fine for me. 
I have set up a Spigot server with no plugins (don't know if your server had any plugins installed) and tried with MoreCommands and BetterFoliage installed client side (I didn't install all the other mods because simply from having the file names I didn't find all of them only by searching) and there were no problems at all for me.
Since the last update I don't have any problems in singleplayer as well. I'm pretty sure that there's a conflict possibly involving more than only two mods. However as I said I just wasn't able to reproduce this for myself so there's no way for me to investigate this further. 

The last thing I know to do is you could send me your entire mods folder or give me the exact download links for every of your mods (because as I said, I just didn't find all of them using Google) and I'll try it again with all of your mods. 
The best thing would be if I had the exact same configuration as you (same mods, same worlds, etc.) but I think only the mods should matter. The other option is just to say screw it, I can do without MoreCommands and we close this because if I can't see this bug for myself we're not making any progress in getting this fixed. 

Just tell me whether I should have another look at it (but then I really need an exact description how to reproduce this bug including download links for your mods, etc.) or whether we should just leave it as it is and close this issue because nobody else reported it and you can do without MoreCommands.

**Comment by Tsoccerguy3** [comment] 2017-05-21 15:23
http://sdrv.ms/TPcx5v , I zipped up the 1.11.2 folder . I just tested again and bug still there

Windows 10 RS2 1703
Java 8 b131
AMD drivers 17.5.2  (Maybe , If your developing using Nvidia Hardware , this could be a reason you cant see bug , just a idea )

Try these plugins out on server mc.hippout.com   and /warp ice

**Comment by Tsoccerguy3** [comment] 2017-05-24 22:54
It's not related to video drivers , tested on Intel , nVidia and AMD . same problem . seems to be conflicting with a few other mods on client side

**Comment by MrNobody98** [comment] 2017-05-28 01:40
I finally figured it out. This bug was caused by a flawed part of code which existed in this form since the early days of MoreCommands and never caused trouble to me because there are multiple factors which are required for this bug to appear which I can't influence at all. I even managed to get the world to render properly about 30% the times I logged into the server with exactly the mods you provided me (It's a timing-related issue which can depend on network speed, java's thread scheduling, pc power, number of mods installed, etc.). 

I used this oppurtunity to make some major changes to the code to structure it better which is why it took some days to do this for all versions and why the changes are quite a lot, the actual fix was relatively easy to do (Although it required quite a hacky workaround to achieve the same things without the flawed part of the code),

Download links are the same, just redownload.

**Closed by MrNobody98** 2017-05-28 01:40 UTC
